# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: refresh latest version
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.RACCBOT_PROD_AWS_HOST }}
          username: ${{ secrets.RACCBOT_PROD_AWS_USER }}
          key: ${{ secrets.RACCBOT_PROD_AWS_KEY }}
          port: ${{ secrets.RACCBOT_PROD_AWS_PORT }}
          script: |
            cd bot
            wget -P ./ https://github.com/dorival/raccbot-discord/archive/v1.1.0.tar.gz
            tar -C ./ -xvf v1.1.0.tar.gz
            rm v1.1.0.tar.gz
            pm2 delete raccbot-discord
            rm -r raccbot-discord/
            mv ./raccbot-discord-v1.1.0 ./raccbot-discord
            cd raccbot-discord
            echo 'TOKEN=${{ secrets.RACCBOT_PROD_DISCORD_TOKEN }}' > ./.env
            npm i
            pm2 start index.js --name raccbot-discord
